### ISSUE TITLE
Plans ahead?

### ISSUE THREAD

**Issue by Skyhawk1207** [cutefishos/screenlocker#8]
I know this might not be the right place to ask this, but since I'm finding no other way to get in touch with the dev team, I decided to ask here. CutefishDE and CutefishOS seems like a real game changer in Linux, with potential to stand side-by-side with the big names like GNOME and KDE. 

**But what are the dev's plans for Cutefish?** 

- Do you plan to only continue on the DE, or are you thinking of new releases for the OS as well? 
- When can we expect updates on the OS?
- Are the commits being done to the various repositories here available as updates on the DE via apt?

I really appreciate the effort and the idea of CutefishOS. Would love to hear from the developers.

**Comment by DanielVenturini** [comment]
Hey, that is a great discussion we could have.

I had CutfishDE installed because it's a fantastic DE, but I faced so many issues with the interface that I also opened a issue here.

I really would like to see Cutefish as a mature project evolving over and over more, and I know it has a such potential to that.

I believe, @Skyhawk1207, we could open a discussion [here](https://github.com/orgs/cutefishos/discussions/new/choose) and try to reach the developers there.

**Comment by Skyhawk1207** [comment]
Thanks for showing me the right place to put up my question @DanielVenturini! I've posted a Q&A there ([link](https://github.com/orgs/cutefishos/discussions/23#discussion-7616693)). Hopefully, we hear some good news from the devs, as I am itching to try something fresh when it comes to DE. I frankly feel there's no other DE which has a modern and sleek look out of the box with no customization.
